### ISSUE TITLE
业务管理模块并网上传文件失败是什么原因以及政策上传文件也不成功要怎么解决

### ISSUE THREAD

**Issue by zzb12313** [MlllXavier/PhotovoltaicBusiness#1]

**Comment by MlllXavier** [comment]
我们当时是准备将前端运行文件和后端运行文件放在同一个服务器上，于是把文件上传直接放到前端上，文件保存在前端文件里的一个文件夹中，后端只往数据库里放文件的位置信息，您可以检查一下前端代码。另外我们所有的文件上传都是用的一种方式，您说的两个上传文件失败的原因应该是同一个问题

**Comment by MlllXavier** [comment]
我们当时是准备将前端运行文件和后端运行文件放在同一个服务器上，于是把文件上传直接放到前端上，文件保存在前端文件里的一个文件夹中，后端只往数据库里放文件的位置信息，您可以检查一下前端代码。另外我们所有的文件上传都是用的一种方式，您说的两个上传文件失败的原因应该是同一个问题

**Comment by zzb12313** [comment]
解决了，是文件路径问题
